// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfqwkjepyippncfrenzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcXdramVweWlwcG5jZnJlbnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjg5NTAsImV4cCI6MjA1ODk0NDk1MH0.YpjDE6Hr8vg_JxeL1RJuHdF6Fgj6mrXb68Vd0H3_4mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);